add board view
Hair-In-Tongue/25words pull request #15
Opened 2022-03-23 14:11 UTC by Mamoonah

2022-03-24 19:11 UTC, ShellModule commented on client/web/src/components/Bid/Bid.styled.ts
> +
Halo kurwa co tu robi interfejs z jednym propem
Prosze go wyjebac szybciutko

2022-03-24 19:13 UTC, ShellModule commented on client/web/src/components/Bid/Bid.styled.ts
> +    place-self: center;
Dawaj te wszystkie modyfikatory css jak :after czg :before po ogolnych zasadach

2022-03-24 19:29 UTC, ShellModule commented on client/web/src/components/Bid/Bid.tsx
> +        console.log(dupa)
??

2022-03-25 12:40 UTC, Mamoonah commented on client/web/src/components/Bid/Bid.tsx
> +        console.log(dupa)
Przecież to nie jest moje. Wspominałem to ostatnio. Wyskoczyło jako zmiany w kodzie bo przeniosłem ten komponent we właściwe miejsce :)

2022-03-25 14:22 UTC, ShellModule commented on client/web/src/components/Cards/Cards.styled.ts
> +}
Zamiast robic interfejsy z jednym propem zrob w kodzie wyłuskanie ({guessed}: boolean)=>{} chyba tak sie pisalo.
Interjest z jednym propem jest bez sensu

2022-03-25 14:27 UTC, ShellModule commented on client/web/src/components/Cards/Cards.tsx
> +    const { playerState, userData }: IGameProps = useGameContext()
Board? Plik nazywa sie Cards

2022-03-25 14:28 UTC, ShellModule commented on client/web/src/components/Cards/Cards.tsx
> +                </PlayingCard>
Moze warto by bylo zrobic z poiedynczej karty komponent? W przyszlosci moze uzyjemy go w innych miejscach i jest kod czytelniejszy

2022-03-25 14:29 UTC, ShellModule requested changes
Poprosze zapierdalac szybciutko

2022-03-27 09:59 UTC, merged